### ISSUE TITLE
username-filter does not work

### ISSUE THREAD

**Issue by linos22** [lithnet/pan-ra-proxy#4]
Hi Ryan,

I use _username-filter="^([0-9A-Fa-f]{12})"_ but still see that I receive usernames like "c83c8576d732" at the palo alto device.
regexr.com tells me that my regex should be fine.

Can you please check the code?

thanks for this
![OA1ZYO4K](https://user-images.githubusercontent.com/42517601/69365764-daba2680-0c49-11ea-8c07-f80aa939d4d9.png)
![pidkxuWV](https://user-images.githubusercontent.com/42517601/69365766-daba2680-0c49-11ea-84ae-7c3be0403d00.png)
![lgrIaV2s](https://user-images.githubusercontent.com/42517601/69365767-daba2680-0c49-11ea-8bd8-a7affe3a34c0.png)

**Comment by ryannewington** [comment]
@linos22 try this build 

[Lithnet.Pan.RAProxy.Setup.zip](https://github.com/lithnet/pan-ra-proxy/files/3899012/Lithnet.Pan.RAProxy.Setup.zip)

**Comment by linos22** [comment]
Until now it works like a charm.
I will keep you posted

Thank you very much
