### ISSUE TITLE
PAN-OS NO XML API login

### ISSUE THREAD

**Issue by calibregtx** [lithnet/pan-ra-proxy#6]
I was unable to get the XML API to my firewall after logging in
troubleshot steps
-make sure NPS working fine
-make sure NPS accounting set to default directory and port 1813
-make sure logging in user is fine, via NTRadPing Test Utility
-there are NPS logs successfull
->there are no application log regarding PAN-RA-Proxy other than service start/stop, it was read 'service1'
->there are no XMLAPI logs to the FW whenever login occurs

**Comment by ryannewington** [comment]
Hi @calibregtx 

I'd first make sure your network device is sending account events. Turn on accounting logging on the NPS server and make sure you can see events coming in.

If you can see those logs, then download [debugview](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)
Run this as admin, and from the capture menu select Capture Win32 and Capture Global Win32.

This will show you the internal logs of the app itself. If nothing is appearing, but you can see accounting logs in NPS, then NPS is not configured to forward the logs to the proxy.

If you do see logs, then you will be able to see any errors or reasons why the PAN might not be receiving the data. However, these errors should be appearing in the event log anyway.

**Comment by mspell-foreflight** [comment]
Hey @ryannewington

You mention NPS forwarding logs to the PanRAProxy. The documentation says that the proxy listens on the port you specify in the config file for accounting messages, but nothing about NPS needing to be configured to forward logs to the service. How do I accomplish that?

I'm only see event 3101 in my event logs (A RADIUS message was received from an unknown RADIUS host), and nothing in debugview with the captures you recommended. NPS is working just fine to authenticate users and allow network connections and I have Accounting logging set to record to log file in the default location.

Thanks!



<br class="Apple-interchange-newline">

**Comment by ryannewington** [comment]
You need to create a new RADIUS server and group for 127.0.0.1, listening on the port you specify in the pan Ra proxy config.

https://learn.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-crp-rrsg-configure

Then in your connection policies you configure the policy to send accounting messages to the "remote" radius server. 

So the accounting messages get delivered from the network device to the NPS server, which then relays them to the PAN RA Proxy listening on local host, which then converts them to API calls direct to the Palo device.
