### ISSUE TITLE
No debug output to Application log

### ISSUE THREAD

**Issue by c-cuthbert** [lithnet/pan-ra-proxy#7]
Hi there. 

I have installed RADIUS Accounting to Palo-Alto Networks Firewall User-ID Agent and the service has started fine. I've edit the .config file, however I'm having difficulty getting accounting information to pass through to the firewall. I'm not seeing any logging or debug messages pass through to the Application eventlog. I've added debug-enabled="true" setting, but still receive no information in the event log.

The service is running on Windows 2019 on the server with NPS installed.

I sent an email before I realise I could log a support ticket, apologies for the duplication.

Kind Regards

Christian

**Comment by ryannewington** [comment]
Hi @c-cuthbert 

I'd first make sure your network device is sending account events. Turn on accounting logging on the NPS server and make sure you can see events coming in.

If you can see those logs, then download [debugview](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)
Run this as admin, and from the capture menu select Capture Win32 and Capture Global Win32.

This will show you the internal logs of the app itself. If nothing is appearing, but you can see accounting logs in NPS, then NPS is not configured to forward the logs to the proxy.

If you do see logs, then you will be able to see any errors or reasons why the PAN might not be receiving the data. However, these errors should be appearing in the event log anyway.

Let me know how you go
