### ISSUE TITLE
Server install issue

### ISSUE THREAD

**Issue by wagstr** [lithnet/pan-ra-proxy#8]
Hello,
I have tried installing pan-ra-proxy on 3 different servers and it fails on starting service saying there are insufficient rights, even changing the log on user to one I know for a fact can start services fails too. I have installed it on my workstation on same domain no problem. 

![image](https://github.com/lithnet/pan-ra-proxy/assets/170519016/3eafb52b-448d-46da-935b-80805308e9bd)

Thanks for any assistance!

**Comment by c-cuthbert** [comment]
Check .net version, I had same problem. From memory requires 4.8

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: wagstr ***@***.***>
Sent: Wednesday, May 22, 2024 8:31:34 PM
To: lithnet/pan-ra-proxy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lithnet/pan-ra-proxy] Server install issue (Issue #8)


Hello,
I have tried installing pan-ra-proxy on 3 different servers and it fails on starting service saying there are insufficient rights, even changing the log on user to one I know for a fact can start services fails too. I have installed it on my workstation on same domain no problem.

image.png (view on web)<https://github.com/lithnet/pan-ra-proxy/assets/170519016/3eafb52b-448d-46da-935b-80805308e9bd>

Thanks for any assistance!

**Comment by wagstr** [comment]
Thanks! That did the trick.

**Comment by ryannewington** [comment]
Thanks for reporting this @wagstr and @c-cuthbert for providing the solution. The installer was checking for .NET 4.6, not 4.8. I'm pushing a new build at the moment to address this. It will be fixed in v1.1.3
