### ISSUE TITLE
Extreme Networks AP using ExtremeCloudIQ

### ISSUE THREAD

**Issue by sterion75** [lithnet/pan-ra-proxy#9]
Having an issue with this setup using ExtremeCloudIQ.

I have each AP in as a radius server and using the following rewrite where xxxxxx is our company name

    <username-rewrites output-format="nt4">
      <username-rewrite match="^([^\.\@\\]+)$" replace="empire\$1"/>
      
    </username-rewrites>

I have two issues. Firstly when someone roams AP there is a login->logout->login->logout which seems to effectively cut off the persons internet requiring them to sign in again, however they probably dont see the signin page as they dont have a decrypt cert installed on their own device so just get this page cannot be displayed(for the authentication portal). Either way we dont want the portal to ever come up and authentication should be handled by radius and the wifi profile only. I am guessing with so many AP's reporting in these events might not even come in the right order as there is no aggregated controller keeping track of sessions?

This is what Palo sees. As you can see there is login logout login logout.
![image](https://github.com/user-attachments/assets/e727ab56-1327-4e3e-a209-97efb84d45c3)

The second issue we have devices connecting with device certs to our core network and the software sees this as HOST/. Ideally I would just want to filter or ignore those completely in the rewrite so they arent submitted or looked up to save time.

Any advice would be appreciated

**Comment by ryannewington** [comment]
Hi @sterion75 

You can filter our usernames using by adding a regular expression to a attribute called `username-filter` in your config file

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="ra-proxy-config" type="Lithnet.Pan.RAProxy.RAProxyConfigurationSection,Lithnet.Pan.RAProxy"/>
  </configSections>

  <ra-proxy-config username-filter="xxx">
    <pan-api-endpoints batch-size="200" batch-wait="50">
      <pan-api-endpoint url="https://test-fw/api/" api-key="xxx"/>
    </pan-api-endpoints>

   <!-- optionally re-write incoming user names to a standardized format based on a regular expression -->

    <username-rewrites output-format="nt4">
      <!--<username-rewrite match="^([^\.\@\\]+)$" replace="domain\$1"/>
      <username-rewrite match="^(.+)@domain.local$" replace="domain\$1"/>-->
    </username-rewrites>

    <radius-servers>
      <radius-server host="127.0.0.1" secret="test"/>
      <radius-server host="myhost" secret="test"/>
    </radius-servers>
    <radius-client accounting-port="18131"/>
  </ra-proxy-config>

  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>
  </startup>
</configuration>
```

However, i dont have much helpful advice i can give on the roaming issue. This radius client is just proxying requests as they arrive into the pan API, there's no real opportunity for coordination across a distributed set of nodes.
